inherit_from: configs/scannetpp/scannetpp.yaml
data:
  input_path: data/scannetpp/data/8b5caf3398
  output_path: output/ScanNetPP/8b5caf3398
  scene_name: "8b5caf3398"
  use_train_split: True
  frame_limit: 250
cam:
  H: 584
  W: 876
  fx: 316.3837659917395
  fy: 319.18649362678593
  cx: 438.0
  cy: 292.0
