inherit_from: configs/ScanNet/scannet.yaml
data:
  input_path: /home/liyuanzhu/projects/GSR/MonoGS/datasets/scannet/scene0465_00
  output_path: output/ScanNet/scene0465
  scene_name: scene0465_00
cam: 
  fx: 577.9
  fy: 577.9
  cx: 319.5
  cy: 239.5