inherit_from: configs/TUM_RGBD/tum_rgbd.yaml
data:
  input_path: data/TUM_RGBD-SLAM/rgbd_dataset_freiburg1_desk
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg1_desk/
  scene_name: rgbd_dataset_freiburg1_desk
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 50
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]